export type MenuCommand = "new" | "open" | "save" | "saveAs";

export const IPC = {
  spikeOpen: "spike:open",
  spikeGetBook: "spike:get-book",
  spikePrint: "spike:print",
  printResult: "print:result",
  bookLoadShelf: "book:load-shelf",
  bookOpen: "book:open",
  bookSave: "book:save",
  bookSaveAs: "book:save-as",
  bookSaveDefault: "book:save-default",
  bookDelete: "book:delete-file",
  bookPersistShelf: "book:persist-shelf",
  menuCommand: "menu:command",
  confirmClose: "app:confirm-close",
  allowClose: "app:allow-close",
  settingsLoad: "settings:load",
  settingsSave: "settings:save",
  spellSet: "spell:set",
  imagePick: "image:pick",
  exportPdf: "export:pdf",
  exportChooseDir: "export:choose-dir",
  exportEpub: "export:epub",
  exportDocx: "export:docx",
  importDocx: "import:docx",
  exportTheme: "export:get-theme",
} as const;
