export const IPC = {
  spikeOpen: "spike:open",
  spikeGetBook: "spike:get-book",
  spikePrint: "spike:print",
  printResult: "print:result",
  libraryLoad: "library:load",
  librarySave: "library:save",
  libraryExportBook: "library:export-book",
  settingsLoad: "settings:load",
  settingsSave: "settings:save",
  spellSet: "spell:set",
  imagePick: "image:pick",
  exportPdf: "export:pdf",
  exportEpub: "export:epub",
  exportDocx: "export:docx",
  importDocx: "import:docx",
  exportTheme: "export:get-theme",
} as const;
